server:
  port: 8080
  servlet:
    context-path: /examcard
  tomcat:
    accesslog:
      enabled: true
      directory: ${LOG_PATH}
      prefix: access
      suffix: .log
      pattern: "%t %h %b %m %U %s %Dms"
      rotate: true
      file-date-format: .yyyyMMdd
      max-days: 30
      rename-on-rotate: true
    additional-tld-skip-patterns: "oraclepki.jar, osdt_core.jar, osdt_cert.jar"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examcard
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:/com/examcard/mapper/*.xml

logging:
  level:
    org.apache.catalina: INFO
  file:
    path: ${LOG_PATH}
    name: apl.log

customer:
  application:
    search:
      max:
        count: 1000
rows:
  per:
    page: 30

pagenation:
  size: 10